version: "3.8"
volumes:
  postgres_data:
    external: false
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./manage.py runserver 0.0.0.0:8000
    env_file:
        - .env

#    command: bash
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app:rw

#      args:
#        DEBIAN_FRONTEND: noninteractive
#        BASE_DIR: /usr/src/app/
  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
        - "127.0.0.1:5431:5432"
    env_file:
        - .env