# Generated by Django 4.1.6 on 2023-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
