# Generated by Django 4.1.6 on 2023-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images', width_field=100),
        ),
    ]
