# Generated by Django 4.2 on 2023-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="img",
            field=models.ImageField(upload_to="./images"),
        ),
    ]
