# Generated by Django 4.2 on 2023-04-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotegory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cotegory',
            new_name='category',
        ),
    ]
