# Generated by Django 4.2 on 2023-05-22 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_rename_cotegory_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="CategoryModel",
        ),
        migrations.RenameModel(
            old_name="Product",
            new_name="ProductModel",
        ),
    ]
