# Generated by Django 4.2 on 2023-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_productmodel_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIPModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="URLFromModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url_from", models.URLField()),
                ("now_url", models.URLField()),
            ],
        ),
    ]
