# Generated by Django 4.2 on 2023-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_rename_now_url_urlfrommodel_url_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlfrommodel",
            name="url_to",
            field=models.URLField(help_text="url, which you are going to visit"),
        ),
    ]
